# Generated by Django 4.2.1 on 2023-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yearofgrad',
            field=models.CharField(max_length=255),
        ),
    ]
