# Generated by Django 4.2.1 on 2023-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0002_alter_user_yearofgrad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
