# Generated by Django 4.2.1 on 2023-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buisid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('headquarters', models.CharField(max_length=500)),
                ('websitelink', models.CharField(max_length=10000)),
                ('about', models.CharField(max_length=500)),
                ('industry', models.CharField(max_length=500)),
                ('companysize', models.IntegerField(max_length=500)),
                ('specialities', models.CharField(max_length=1000)),
                ('projects', models.JSONField()),
            ],
        ),
    ]
