# Generated by Django 4.2.1 on 2023-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0004_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='companysize',
            field=models.IntegerField(),
        ),
    ]
