# Generated by Django 4.2.1 on 2023-05-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0005_alter_business_companysize'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pfp',
            field=models.CharField(default='', max_length=255),
        ),
    ]
