# Generated by Django 4.2.1 on 2023-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0006_business_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='companysize',
            field=models.IntegerField(null=True),
        ),
    ]
