# Generated by Django 4.2.1 on 2023-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0007_alter_business_companysize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AlterField(
            model_name='business',
            name='buisid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
