# Generated by Django 4.2.1 on 2023-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0009_alter_business_pfp_alter_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username2',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
