# Generated by Django 4.2.1 on 2023-05-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baguette', '0010_user_username2_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username2',
            new_name='username',
        ),
    ]
